### ISSUE TITLE
Use vagrant-libvirt instead of libvirt

### ISSUE THREAD

**Issue by Crunsher** [sepulworld/aptly-vagrant#16]
The vagrant libvirt plugin is outdated, horrendously so, it is not maintained anymore and does not work with newer vagrant versions.  
Please replace it with vagrant-libvirt

**Comment by sepulworld** [comment]
@Crunsher what exactly are you referring to in this repository?  The Vagrantfile doesn't call for this plugin.  Please show me the file(s) and line numbers of what you are talking about.

The Vagrantfile in this repository uses Virtualbox for a virtual provider:
https://github.com/sepulworld/aptly-vagrant/blob/master/Vagrantfile#L10

**Comment by Crunsher** [comment]
It was actually a problem with the permissions on my local system which caused vagrant to fail. For completeness sake here is the error message I was receiving when running vagrant up:
`The provider 'libvirt' could not be found, but was requested to back the machine 'reposerver'. Please use a provider that exists.`

Sorry for bothering you and have a nice day
