### ISSUE TITLE
Usage of vagrant-librarian-puppet?

### ISSUE THREAD

**Issue by tuxinaut** [sepulworld/aptly-vagrant#20]
It'd be easier to use [vagrant-librarian-puppet](https://github.com/mhahn/vagrant-librarian-puppet) to resolve **puppet module** dependencies instead of git **submodules**.

**Comment by sepulworld** [comment]
Thanks Denny. I was considering switching over to R10k but if
vagrant-librarian-puppet is a better option then let's do that.

On Tue, Jan 12, 2016, 8:22 AM Denny Schäfer <notifications@github.com>
wrote:

> It'd be easier to use vagrant-librarian-puppet
> <https://githubcom/mhahn/vagrant-librarian-puppet> to resolve *puppet
> module* dependencies instead of git *submodules*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sepulworld/aptly-vagrant/issues/20>.
>
-- 
-Zane

**Comment by sepulworld** [comment]
Ok so I looked into using vagrant-librarian-puppet but it is broken with Vagrant 1.8.1 presently

https://github.com/mhahn/vagrant-librarian-puppet/issues/47

So, I went with r10k for now.  We can circle back on vagrant-librarian-puppet later.

**Comment by sepulworld** [comment]
https://github.com/sepulworld/aptly-vagrant/pull/21
